# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$fill\
$c\
$cmake\
$golang\
$lua\
$nodejs\
$python\
$rust\
$zig\
$cmd_duration\
$line_break\
$jobs\
$character"""

add_newline = true

[aws]
disabled = true

[c]
format = "[$symbol($version(-$name) )](bold blue)"

[cmd_duration]
disabled = false
min_time = 500
format = '[took $duration](bold yellow)'

[fill]
symbol = " "

[line_break]
disabled = false

[golang]
format = '[$symbol($version )($mod_version )](bold cyan)'
symbol = "Go "

[nodejs]
format = "[$symbol($version )](bold green)"
symbol = "NodeJS "

[package]
disabled = true
format = "[$symbol$version]($style) "
symbol = "Packaged "

[rust]
format = "[$symbol($version )]($style)"
symbol = "Rust "
